# Generated by Django 4.0.3 on 2022-05-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetbalance',
            name='balance',
            field=models.CharField(default=0, max_length=255, null=True),
        ),
    ]
