# Generated by Django 4.0.3 on 2022-05-10 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_deposithistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposithistory',
            name='chain',
        ),
        migrations.RemoveField(
            model_name='deposithistory',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='deposithistory',
            name='to',
        ),
    ]
