# Generated by Django 4.0.3 on 2022-05-10 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_deposithistory_chain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposithistory',
            name='amount',
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='history',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='saved_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
