# Generated by Django 4.0.3 on 2022-05-10 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_deposithistory_amount_deposithistory_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposithistory',
            old_name='saved_on',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='deposithistory',
            name='history',
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='amount',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='chain',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deposithistory',
            name='to',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
