# Generated by Django 4.0.4 on 2022-05-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_deposithistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposithistory',
            name='status',
            field=models.CharField(choices=[('succesful', 'successful'), ('not-successful', 'not-successful')], default='not-successful', max_length=50),
        ),
    ]
