# Generated by Django 4.0.4 on 2022-05-26 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='initiated_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='deposit',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
