# Generated by Django 4.0.4 on 2022-05-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_deposit_initiated_on_deposit_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=255, null=True),
        ),
    ]
