# Generated by Django 4.0.4 on 2022-05-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_deposit_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=255),
        ),
    ]
