# Generated by Django 4.0.3 on 2022-04-09 05:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('recieved_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
