# Generated by Django 4.0.3 on 2022-04-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ads_images')),
                ('video', models.FileField(blank=True, null=True, upload_to='ads_videos')),
                ('details', models.TextField()),
            ],
        ),
    ]
