# Generated by Django 4.0.4 on 2022-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_profile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
